# Generated by Django 5.1.5 on 2025-02-05 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_follwers'),
        ('auth', '0013_user_following'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follwers',
            new_name='Followers',
        ),
        migrations.RenameIndex(
            model_name='followers',
            new_name='account_fol_created_2b444c_idx',
            old_name='account_fol_created_1c3c7c_idx',
        ),
    ]
