# Generated by Django 5.1.5 on 2025-02-06 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venv', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action_id', models.PositiveIntegerField(default=0)),
                ('action_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_content_type', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='action_acti_created_4364ca_idx')],
            },
        ),
    ]
