# Generated by Django 5.1.5 on 2025-02-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
